In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\Dell\OneDrive\Documents\DATA ANALYSIS PROJECT\Customer Churn & Customer Behavior Analysis\EXCEL\DATA TO PERFORM ON SQL AND LIBRARIES.csv")
df

,Customer_ID,Signup_Date,Customer_Name,Gender,Age,City,State,Customer_Segment,Subscription_Plan,Acquisition_Channel,...,Last_Purchase_Date,Days_Since_Last_Purchase,Monthly_Logins,Email_Open_Rate,Support_Tickets,Returns,Satisfaction_Score,Discount_Usage_Rate,Customer_Status,Churn_Flag
0,CUST10001,25-06-2024,Customer 1,Male,30,Ahmedabad,Gujarat,Standard,Monthly,Google Ads,...,23-12-2025,8,15,0.57,3,0,5.0,0.16,Active,0
1,CUST10002,16-05-2025,Customer 2,Female,32,Bengaluru,Karnataka,Basic,Quarterly,Referral,...,02-11-2025,59,11,0.14,0,0,4.7,0.36,Active,0
2,CUST10003,22-10-2025,Customer 3,Female,21,Indore,Madhya Pradesh,Basic,Annual,Google Ads,...,22-10-2025,69,6,0.34,1,0,3.8,0.38,At Risk,0
3,CUST10004,13-10-2024,Customer 4,Male,18,Bhopal,Madhya Pradesh,Basic,Monthly,Email Campaign,...,11-12-2025,20,14,0.58,0,0,4.2,0.77,Active,0
4,CUST10005,26-12-2025,Customer 5,Male,21,Surat,Gujarat,Standard,Quarterly,Email Campaign,...,26-12-2025,4,3,0.62,1,1,4.4,0.39,Active,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,CUST17996,02-11-2025,Customer 7996,Male,24,Nagpur,Maharashtra,Standard,Monthly,Social Media,...,22-11-2025,39,5,0.34,1,0,4.3,0.46,Active,0
7996,CUST17997,27-07-2024,Customer 7997,Female,28,Mumbai,Maharashtra,Standard,Monthly,Social Media,...,26-10-2025,66,10,0.51,1,0,2.9,0.30,At Risk,0
7997,CUST17998,24-09-2025,Customer 7998,Male,32,Nashik,Maharashtra,Premium,Annual,Google Ads,...,03-12-2025,28,7,0.41,2,3,4.6,0.36,Active,0
7998,CUST17999,01-05-2024,Customer 7999,Male,44,Lucknow,Uttar Pradesh,Standard,Annual,Social Media,...,19-12-2025,12,5,0.39,4,0,4.1,0.32,Active,0
7999,CUST18000,20-11-2024,Customer 8000,Male,38,Lucknow,Uttar Pradesh,Basic,Annual,Referral,...,12-12-2025,19,12,0.36,1,0,4.1,0.44,Active,0

In [9]:
df.shape
df.columns
df.dtypes
df.describe()

,Age,Total_Orders,Average_Order_Value,Total_Spend,Days_Since_Last_Purchase,Monthly_Logins,Email_Open_Rate,Support_Tickets,Returns,Satisfaction_Score,Discount_Usage_Rate,Churn_Flag
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,32.282125,6.956750,1434.918456,11537.942229,41.485500,7.262375,0.426878,1.168375,0.626500,3.948600,0.293000,0.054125
std,8.578927,4.043937,653.697191,11286.545088,26.706585,2.926022,0.174743,1.132447,1.017412,0.667923,0.161227,0.226278
min,18.000000,1.000000,300.000000,406.600000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,26.000000,4.000000,923.912500,3820.272500,22.000000,5.000000,0.300000,0.000000,0.000000,3.500000,0.170000,0.000000
50%,32.000000,6.000000,1275.495000,7448.915000,36.000000,7.000000,0.420000,1.000000,0.000000,4.000000,0.270000,0.000000
75%,38.000000,9.000000,1789.995000,15199.735000,56.000000,9.000000,0.550000,2.000000,1.000000,4.400000,0.400000,0.000000
max,65.000000,27.000000,3893.120000,90322.860000,180.000000,19.000000,0.940000,8.000000,10.000000,5.000000,0.890000,1.000000

In [10]:
df.isna().sum()

Customer_ID                 0
Signup_Date                 0
Customer_Name               0
Gender                      0
Age                         0
City                        0
State                       0
Customer_Segment            0
Subscription_Plan           0
Acquisition_Channel         0
Total_Orders                0
Average_Order_Value         0
Total_Spend                 0
Last_Purchase_Date          0
Days_Since_Last_Purchase    0
Monthly_Logins              0
Email_Open_Rate             0
Support_Tickets             0
Returns                     0
Satisfaction_Score          0
Discount_Usage_Rate         0
Customer_Status             0
Churn_Flag                  0
dtype: int64

In [11]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
7995    False
7996    False
7997    False
7998    False
7999    False
Length: 8000, dtype: bool

In [12]:
total_customer = df["Customer_ID"].count()
total_customer

np.int64(8000)

In [14]:
average_customomer_spendig=df["Total_Spend"].mean()
average_customomer_spendig

np.float64(11537.94222875)

In [4]:
top_10_customer_by_spending=df.groupby("Customer_Name")["Total_Spend"].sum().sort_values(ascending=False).head(10)
top_10_customer_by_spending

Customer_Name
UNKNOWN          141810.99
Customer 6443     90322.86
Customer 3578     71580.32
Customer 5749     71020.94
Customer 2538     70854.02
Customer 1065     67382.58
Customer 4467     66967.49
Customer 955      66915.30
Customer 7348     65277.35
Customer 5839     64796.71
Name: Total_Spend, dtype: float64

In [5]:
average_spending_by_segment=df.groupby("Customer_Segment")["Total_Spend"].mean()
average_spending_by_segment

Customer_Segment
Basic        4167.095058
Premium     32298.513789
Standard    11958.661496
Name: Total_Spend, dtype: float64

In [7]:
average_spending_by_plans=df.groupby("Subscription_Plan")["Total_Spend"].mean()
average_spending_by_plans

Subscription_Plan
Annual       11270.843693
Monthly      11516.155399
Quarterly    11789.691710
Name: Total_Spend, dtype: float64

In [10]:
churned_customers=(df["Churn_Flag"]==1).sum()
churned_customers

np.int64(433)

In [14]:
churn_rate=(churned_customers/total_customer)*100
churn_rate

np.float64(5.4125)

In [17]:
churn_rate_by_segement=df.groupby("Customer_Segment")["Churn_Flag"].mean() * 100
churn_rate_by_segement

Customer_Segment
Basic       7.233573
Premium     2.782324
Standard    4.340938
Name: Churn_Flag, dtype: float64

In [19]:
camparison=df.groupby("Churn_Flag")[["Total_Spend","Total_Orders","Monthly_Logins"]].mean().rename(index={0:"active",1:"churned"})
camparison

             Total_Spend  Total_Orders  Monthly_Logins
Churn_Flag
active      11684.190764      6.999339        7.537862
churned      8982.139307      6.212471        2.448037

In [ ]:
#NUMPY

In [21]:
#Convert Total_Spend into a NumPy array.
spending = np.array(df["Total_Spend"])
spending

array([14419.09,   760.58,  3673.3 , ..., 55499.46, 17899.98,  4560.55],
      shape=(8000,))

In [25]:
#Calculate mean spending
mean_spending = np.mean(spending)
print(mean_spending)

11537.94222875

In [26]:
#Calculate median spending
median_spending = np.median(spending)
print(median_spending)

7448.915

In [27]:
#Calculate standard deviation
std_spending = np.std(spending)
print(std_spending)

11285.83965738289

In [28]:
#Find minimum and maximum spending
minimum = np.min(spending)
maximum = np.max(spending)

print("Minimum:", minimum)
print("Maximum:", maximum)

Minimum: 406.6
Maximum: 90322.86

In [29]:
#Calculate 25th and 75th percentile
p25 = np.percentile(spending, 25)
p75 = np.percentile(spending, 75)

print("25th Percentile:", p25)
print("75th Percentile:", p75)

25th Percentile: 3820.2725
75th Percentile: 15199.735

In [30]:
#Compare mean spending of Churned vs Active customers
churned_spending = np.mean(df[df["Churn_Flag"] == 1]["Total_Spend"])
active_spending = np.mean(df[df["Churn_Flag"] == 0]["Total_Spend"])

print("Churned Mean Spending:", churned_spending)
print("Active Mean Spending:", active_spending)

Churned Mean Spending: 8982.139307159354
Active Mean Spending: 11684.190763843004